version: '3'
services:
  app:
    build: .docker/
    tty: true
    volumes:
      - .:/var/www/html
    networks:
      - payment-processing-net
    depends_on:
      db:
        condition: service_healthy
  web:
    image: nginx:1.15.0-alpine
    tty: true
    volumes:
      - .:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - payment-processing-net
    depends_on:
      - app
  db:
    image: mariadb:10.3
    tty: true
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=${DB_DATABASE:-local}"
      - "MYSQL_USER=${DB_USERNAME:-root}"
    volumes:
      - "dbdata:/var/lib/mysql"
    command: "--innodb_use_native_aio=0"
    healthcheck:
      test: '/usr/bin/mysql --user=${DB_USERNAME:-root} --database=${DB_DATABASE:-local} --execute="SHOW DATABASES;"'
    networks:
      - payment-processing-net
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - payment-processing-net
networks:
  payment-processing-net:
    driver: bridge
volumes:
  "dbdata":
    driver: local
