#!/usr/bin/env bash

cd /var/www/html/ \
  && composer install \
  && [ -f ".env" ] || cp .env.example .env \
  && php artisan key:generate \
  && chmod -R 777 storage bootstrap/cache .env \
  && php artisan migrate --seed

php-fpm